#!/usr/local/bin/python3

def kmer_counting(dna, k_size = 2, min_found = 3):
    kmersfound = []
    kmerrange = list(range(0,len(dna)))
    for startingbase in kmerrange :
        if (startingbase + k_size) < len(dna) + 1 :
            seqout = dna[startingbase : startingbase + k_size]
            kmersfound = kmersfound + [seqout]
    nonredundantset = list(set(kmersfound))
    frequent_kmers = []
    for kmerfrequencies in nonredundantset :
        if kmersfound.count(kmerfrequencies) > min_found :
            frequent_kmers = frequent_kmers + [kmerfrequencies]
    return frequent_kmers
